### Get
GET http://127.0.0.1:5000

### REGISTER A USER POST /AUTH/SIGNUP
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json 

{
    "name": "Daniel Akande",
    "email": "danielakande33@gmail.com",
    "password": "e",
    "confirmPassword": "e"
}

### LOGIN A USER POST /AUTH/LOGIN
POST http://127.0.0.1:5000/auth/login
Content-Type: application/json 

{
    "email": "Daniel",
    "password": "ddd"
}

### RESET A USER PASSWORD POST /AUTH/RESETP
POST http://127.0.0.1:5000/auth/reset
Content-Type: application/json 

{
    "email": "dddddd"
}